### ISSUE TITLE
Kafka Logs not coming up on Kibana using Filebeat and Logstash with ES on Kubernetes

### ISSUE THREAD

**Issue by etashsingh** [bitnami/bitnami-docker-kafka#127]
**Description**

We are running the latest version of Bitnami Kafka on a Kubernetes cluster. For log aggregation, we are using the Elastic Stack (Filebeat, Logstash, Elasticseach, and Kibana). We have set up Rancher for Kubernetes cluster management. What we noticed a few days back was that the Kafka Logs were not available in Kibana although it is available in Filebeat container through volume mounts and other application logs are coming up as well.

**Steps to reproduce the issue:**

1. Run a kafka pod
2. Create Elastic stack pipeline with filebeat as a DaemonSet

**Describe the results you received:**

Logs not showing on Kibana

**Describe the results you expected:**

Logs should come up on Kibana without extra configurations
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`

```
19.3.12
```

**Comment by marcosbc** [comment]
Hi @etashsingh, sorry but I didn't understand your setup properly. How are you configuring Filebeat to read/obtain Kafka logs? Did it work before with the Bitnami Kafka Docker image?

Please provide detailed information (i.e. including env. vars) so we can try to reproduce it on our side.

**Comment by etashsingh** [comment]
Filebeat is running as a DaemonSet i.e one container replica on each node of the cluster. Basically Filebeat mounts the /var/log/containers directory present on the host machine. This architecture is working for other application pods but not for Bitnami Kafka.
This is the Filebeat configurations. We are using the Helm chart for Kafka
```
filebeat.inputs:
- type: docker
  containers.ids:
  - "*"
  processors:
  - add_kubernetes_metadata:
      host: ${NODE_NAME}
      matchers:
      - logs_path:
          logs_path: "/var/log/containers/"

output.logstash:
  hosts: ['logstash-logstash:5044']

**Comment by marcosbc** [comment]
Hi @etashsingh, does the logs get sent to Logstash? Or is the problem on the Logstash side (and not Kibana)?

Unfortunately I lack experience with the ELK stack, but my understanding is that the Kafka chart itself is working fine and the problem is in the ELK stack side.

The only thing that occurs to me that is different from a non-Bitnami deployment is logs related to the Bitnami container initialization that could get in the way of Kafka logs. You could try to deploy the chart with this change to see if it would have any effect:

```
diff --git a/bitnami/kafka/templates/statefulset.yaml b/bitnami/kafka/templates/statefulset.yaml
index e9b5ce8f9..6a831eaf8 100644
--- a/bitnami/kafka/templates/statefulset.yaml
+++ b/bitnami/kafka/templates/statefulset.yaml
@@ -135,6 +135,8 @@ spec:
           args: {{- include "kafka.tplValue" (dict "value" .Values.args "context" $) | nindent 12 }}
           {{- end }}
           env:
+            - name: BITNAMI_QUIET
+              value: "true"
             - name: BITNAMI_DEBUG
               value: {{ ternary "true" "false" .Values.image.debug | quote }}
             - name: MY_POD_IP
```

NOTE: Unfortunately with this, you would lose any logs related to the initialization. This also includes errors and warnings that would not be shown.
