### ISSUE TITLE
Packages with Known vulnerabilities in kafka:2.8.0-debian-10-r88

### ISSUE THREAD

**Issue by rkandasamy-lenovo** [bitnami/bitnami-docker-kafka#189]
Packages with Known vulnerabilities in kafka:2.8.0-debian-10-r88
Refer [kafka 2.8.0-debian-10-r88.pdf](https://github.com/bitnami/bitnami-docker-kafka/files/7083478/kafka.2.8.0-debian-10-r88.pdf)

![image](https://user-images.githubusercontent.com/77686255/131494189-a8008cfe-772c-4cc1-a412-bb83504d1920.png)

**Comment by carrodher** [comment]
Thanks for using the Bitnami container images! Bitnami releases a new revision (`-rXX`) for all the container images on daily basis, see https://github.com/bitnami/bitnami-docker-kafka/commits/master. The main reason to follow this approach is to ensure all the bundled system packages are updated to the latest available version.

This method doesn't guarantee there are no vulnerabilities in all of them since there are some packages with known vulnerabilities that are not fixed in the Debian OS. In those cases, we can't do anything apart from wait until a new version patching the issue appears in the system package manager of the distro.

For this specific container image, you can take a look at the latest revision (`-r89`) in the [Quay report](https://quay.io/repository/bitnami/kafka/manifest/sha256:78658a5f6c9c184f4a93a52e39cdfe5b6c2b59fac3a70ce5c713ce7469fb5255?tab=vulnerabilities
) (please, ensure to click on the "Only show fixable" checkbox):

![Screenshot 2021-09-01 at 07 55 27](https://user-images.githubusercontent.com/13216600/131620692-d8b65228-0e0d-4c03-b371-74d6b5438898.png)


The same validation can be executed using another CVE scanner such as Trivy:
```console
$ trivy --ignore-unfixed --vuln-type os bitnami/kafka:2.8.0-debian-10-r89
2021-09-01T06:10:21.735Z	INFO	Detecting Debian vulnerabilities...

bitnami/kafka:2.8.0-debian-10-r89 (debian 10.10)
================================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

You can find more info about Bitnami processes regarding CVEs and Vulnerability scanners at https://docs.bitnami.com/kubernetes/open-cve-policy/

**Comment by rmkanda** [comment]
Thanks @carrodher for checking the issue.
I am using a different scanner. There are few fixable  vulnerabilities. The vulnerabilities are on the library not on the OS packages.

![image](https://user-images.githubusercontent.com/38713281/131624836-35d4e1e5-0312-48a7-a2f7-22b2b9ca7703.png)

**Comment by rmkanda** [comment]
Thanks @beltran-rubo for the info. We can close this issue since it is already known and tracked.
