### ISSUE TITLE
docker secrets support

### ISSUE THREAD

**Issue by holms** [bitnami/bitnami-docker-kafka#23]
Would be nice to have docker secrets support: https://docs.docker.com/engine/swarm/secrets/
I wouldn't like to commit docker-compose file to repo with all credentials in it.

**Comment by juan131** [comment]
Hi @holms 

This feature has been requested on other containers (such as MariaDB or MySQL). Check for instance: 

https://github.com/bitnami/bitnami-docker-mysql/issues/44

There's an internal task to include this feature on every container since it's something we're interested on. However, we did not have the chance to work on that yet. 

We'll notify you as soon as we can address it. Thanks for bringing this up!

**Comment by carrodher** [comment]
Unfortunately, I will close this Issue because after reviewing this topic, it was not done in the past nor there are plans to work on it in the short-mid term.

Being side that, since this project is publicly available, would you like to contribute by creating a PR implementing this feature? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
