### ISSUE TITLE
How does KAFKA_CFG_NUM_PARTITIONS work?

### ISSUE THREAD

**Issue by ultimabyte** [bitnami/bitnami-docker-kafka#230]
### Name and Version

bitnami/kafka:2.6.0-debian-10-r29

### What steps will reproduce the bug?

1.  Specific KAFKA_CFG_NUM_PARTITIONS in .yaml
2.  run kubectl apply -f [filename].yaml
3. wait container create
4. access into container 
5. run command kafka-topics.sh --zookeeper zookeeper:2181 --topic topicname --describe

### What is the expected behavior?

Partition in specific topic increase to number that config on KAFKA_CFG_NUM_PARTITIONS 

### What do you see instead?

The partition number isn't match with KAFKA_CFG_NUM_PARTITIONS

**Comment by javsalgar** [comment]
Hi,

I tried the value and could see that the `server.properties` file changed

```
I have no name!@bf85320f8fb2:/$ cat /opt/bitnami/kafka/config/server.properties | grep -C 3 parti
# The default number of log partitions per topic. More partitions allow greater
# parallelism for consumption, but this will also result in more files across
# the brokers.
num.partitions=4
```

About more details on how this should work, my advice would be to directly ask the Kafka developers or check the Kafka documentation. https://kafka.apache.org/documentation/#brokerconfigs_num.partitions

**Comment by carrodher** [comment]
Sorry, we missed the notification generated by the previous answer and until now, due to the automation comment, we didn't see the previous post.

It makes sense, would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
