### ISSUE TITLE
Mounting configMap to /opt/bitnami/kafka/config/log4j.properties causes the libkafka.sh script to fail

### ISSUE THREAD

**Issue by kyle-winkelman** [bitnami/bitnami-docker-kafka#90]
**Description**

I am trying to add an approvement to https://github.com/bitnami/charts/pull/2121 and it requires log4j.properties to be mounted as a configMap.

**Steps to reproduce the issue:**

Deploy the image in Kubernetes with a configMap volume replacing one of the files in the /opt/bitnami/kafka/config directory.

**Describe the results you received:**

When the image starts up the following error occurs:
rm: cannot remove '/opt/bitnami/kafka/config/log4j.properties': Device or resource busy

**Describe the results you expected:**

I expect the image to start up correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is that the libkafka.sh script tries to `rm -rf "$KAFKA_BASEDIR"/config` then `ln -s "$KAFKA_CONFDIR" "$KAFKA_BASEDIR"/config`. The rm fails because the configMap doesn't allow being deleted.

I am looking for a recommended way around this.

The first approach I can think of is to mount the file into /opt/bitnami/kafka/conf then change the `cp -r "$KAFKA_BASEDIR"/config/. "$KAFKA_CONFDIR"` command to include the -n flag to not overwrite my configMap.

The second approach is to mount it at a different location and then use the KAFKA_LOG4J_OPTS environment variable to point to that other location, but this approach wouldn't work for any of the other files in /opt/bitnami/kafka/config.

Not sure if either of these approaches are what the maintainers would like to do though.

**Comment by juan131** [comment]
Hi @kyle-winkelman 

We already faced similar issues in the past in other images. For instance, on [Cassandra image](https://github.com/bitnami/bitnami-docker-cassandra). Let me introduce the workaround we used this in the past for these problems:
- We created a "mounted directory" where we expect users to mount their custom configuration files. See the line below:
  - https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L40
- Then, we created functions to detect when a custom configuration file was mounted and, in that case, copy them to the "real" config directory. See the lines below:
  - https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L322
  - https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L340
  - https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L628
  - https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L362
- Finally, we adapted the Cassandra chart to mount the custom configuration at the "mounted directory" instead of the actual "configuration directory", see:
  - https://github.com/bitnami/charts/blob/master/bitnami/cassandra/templates/statefulset.yaml#L209

Would a solution such as this work for you?

**Comment by kyle-winkelman** [comment]
Closed by #91.
