### ISSUE TITLE
Inter broker user

### ISSUE THREAD

**Issue by javieryanez** [bitnami/bitnami-docker-kafka#95]
Hi,
In the configuration documentation I can see:

> KAFKA_INTER_BROKER_USER: Kafka inter broker communication user. Default: admin. Default: admin

In _ bitnami-docker-kafka/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh _ I can see:

`export KAFKA_INTER_BROKER_USER="${KAFKA_INTER_BROKER_USER:-user}"`

If I understand correctly, I think libkafka.sh should be that:

`export KAFKA_INTER_BROKER_USER="${KAFKA_INTER_BROKER_USER:-admin}"`

**Comment by juan131** [comment]
You're correct @javieryanez !! Thanks for reporting it!

We have two options here:

- A) Adapt `libkafka.sh` so it's `admin` instead of `user`.
- B) Correct the README.md so it says: `Default: user`.

I would go for "option B" in this case to avoid introducing backwards incompatibilities since users using previous versions of the container that didn't modify the default value, are already using `user` as "inter broker communication use".

Would you contribute a PR fixing this?

**Comment by javieryanez** [comment]
Pull request done!

**Comment by juan131** [comment]
Your changes were merged @javieryanez ! I proceed to close this issue as "solved", but please do not hesitate to reopen it if you require further help.
